### ISSUE TITLE
[PkgEval] Stochy may have a testing issue on Julia 0.3 (2015-06-24)

### ISSUE THREAD

**Issue by IainNZ** [null-a/Stochy.jl#1]
[PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) is a script that runs nightly. It attempts to load all Julia packages and run their tests (if available) on both the stable version of Julia (0.3) and the nightly build of the unstable version (0.4). The results of this script are used to generate a [package listing](http://pkg.julialang.org/) enhanced with testing results.
#### On Julia 0.3
- On **2015-06-23** the testing status was `Tests pass.`
- On **2015-06-24** the testing status changed to `Tests fail.`

_This issue was filed because your testing status became worse. No additional issues will be filed if your package remains in this state, and no issue will be filed if it improves. If you'd like to opt-out of these status-change messages, reply to this message saying you'd like to and @IainNZ will add an exception. If you'd like to discuss [PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) please file an issue at the repository. For example, your package may be untestable on the test machine due to a dependency - an exception can be added._

_Test log_:

```
>>> 'Pkg.add("Stochy")' log
INFO: Cloning cache of Stochy from git://github.com/null-a/Stochy.jl.git
INFO: Installing DataStructures v0.3.9
INFO: Installing Docile v0.5.8
INFO: Installing Stochy v0.0.1
INFO: Package database updated

>>> 'Pkg.test("Stochy")' log
INFO: Testing Stochy
INFO: Load Gadfly before Stochy to extend plot function.
Discrete([0=>0.125,2=>0.375,3=>0.125,1=>0.375])
ERROR: assertion failed: |varm(s,m) - shape * scale^2| <= 0.1
  varm(s,m) = 7.886151879640963
  shape * scale^2 = 8.0
  difference = 0.11384812035903735 > 0.1
 in error at error.jl:22
 in test_approx_eq at test.jl:109
 in anonymous at no file:50
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading /home/vagrant/.julia/v0.3/Stochy/test/runtests.jl, in expression starting on line 46

===============================[ ERROR: Stochy ]================================

failed process: Process(`/home/vagrant/julia/bin/julia /home/vagrant/.julia/v0.3/Stochy/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
INFO: No packages to install, update or remove
ERROR: Stochy had test errors
 in error at error.jl:21
 in test at pkg/entry.jl:718
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in cd at pkg/dir.jl:28
 in test at pkg.jl:67
 in process_options at ./client.jl:213
 in _start at ./client.jl:354


>>> End of log
```

**Comment by IainNZ** [comment]
Maybe needs a random seed set before tests run?

**Comment by null-a** [comment]
Thanks for the heads up! I removed those tests a while ago, so I've tagged
the latest revision and submitted a PR to METADATA.jl - hopefully that will
sort it.

**Comment by IainNZ** [comment]
Almost surely will (with probability one?) :+1:
